CREATE TABLE "dyndns" (
  "dyndns_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hostname" varchar UNIQUE NOT NULL,
  "ip_address" varchar,
  "auth_username" varchar NOT NULL,
  "auth_password" varchar NOT NULL,
  "auth_password_salt" varchar NOT NULL,
  "tsig_key_algorithm" varchar,
  "tsig_keyname" varchar,
  "tsig_secret" varchar
);

COMMENT ON COLUMN "dyndns"."hostname" IS 'The registered hostname';

COMMENT ON COLUMN "dyndns"."ip_address" IS 'IP address of the hostname';

COMMENT ON COLUMN "dyndns"."auth_username" IS 'Basic authentication: username';

COMMENT ON COLUMN "dyndns"."auth_password" IS 'Basic authentication: encrypted password';

COMMENT ON COLUMN "dyndns"."auth_password_salt" IS 'Basic authentication: password salt';

COMMENT ON COLUMN "dyndns"."tsig_key_algorithm" IS 'Name of the key algorithm. Valid choices are hmac-md5, hmac-sha1, hmac-sha224, hmac-sha256, hmac-sha384, or hmac-sha512';

COMMENT ON COLUMN "dyndns"."tsig_keyname" IS 'TSIG authentication key';

COMMENT ON COLUMN "dyndns"."tsig_secret" IS 'TSIG authentication secret';

